/**
 * Copyright 2020 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kie.kogito.examples;
unit ThynkService;

//rule getAlert
//   when
//       /claims[ > 0]
//   then
//       alerts.append(new Alert(1));
//   end

rule getAlert2
when
//     /claimDataStream[payer == "payer"]
//     /claimDataStream[payer == "payer"]
//     /claimDataStream[payer == "payer"]
//     codeGroupStream(type == CodeType.ICD9)

then
    alerts.append(new Alert(10));
end

rule test1
when
    /codeGroups[name == "group1"]
then
    alerts.append(new Alert(11));
end

query FindAlerts
  $s : /alerts
end
